# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childlist', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='node',
            old_name='childlist',
            new_name='spacelist',
        ),
    ]
